//for local render languages
const lang = {
    itemStakedTitle: "Staked Validators",
    itemNotStaked: "Not Staked Validators",
    myStake1: "My Stake",
    totalStaked: "Total Staked",
    badgeActive: "Active",
    badgeInactive: "Inactive",
    timeUntilEnd: "Time until end",
    hours: "hr",
    cancel: "Cancel",
    search: "Search..",
    nothingToShow: "Nothing to see here!",
    apr: "Apr",
    copied: "Copied to Clipboard!",
    myActiveStake: "My active stake",
    info4: "Only 25% of active stake can be activated per epoch.",
    read: "Read More",
    annual: "ANNUAL PERCENTAGE RATE",
    totalStake1: "TOTAL STAKE",
    info3: "APR is calculated based on the results of the previous epoch",
    dominance: "DOMINANCE",
    validatorInterest: "VALIDATOR INTEREST",
    info1: "Relative validator weight compared to the average. Lower is better",
    infoTotalStake: "Total stake of validator",
    infoCommission: "A commission that you pay to validator from each reward",
    stakeMore1: "Stake More",
    stake1: "Stake",
    requestWithdraw: "Request Withdraw",
    withdraw1: "Withdraw",
    continue: "Next",
    totalWithdraw: "TOTAL WITHDRAW REQUESTED",
    availableWithdraw: "AVAILABLE FOR WITHDRAW",
    rewardsEmptyTitle: "We did not find any reward records for this validator.",
    rewardsEmptyText: "Read about how rewards are",
    rewardsEmptyLink: "getting credited.",
    reward: "Reward",
    epoch1: "Epoch",
    tabWithdrawals: "Withdrawals",
    tabRewards: "Rewards",
    ok: "Ok",
    progressStaking: "Staking in progress...",
    progressWithdraw: "Withdrawing in process...",
    dontStake: "Don’t stake all coins, leave some (~1 XZO) to pay transaction fees in the future and be able to initiate stake withdrawals.",
    noticeStakingRewards: "Staking rewards will be reinvested and added to the stake.",
    confirm: "Confirm",
    stakingEnteranceTitle: "Stake account has been created successfully",
    stakingEnteranceSubTitle: "It is not fully active immediately, it may take multiple epochs to warm it up.",
    enterAmount: "Enter Amount",
    useMax1: "Use max",
    availableStaking: "Available for staking",
    yourTotalStake: "Your Total Stake",
    titleItemsStake: "These actions will be made",
    stepItem2: "Create Stake Account",
    stepItem3: "Stake to Validator",
    noticeTrying: "You are trying to withdraw more funds than you have.",
    exitValidatorTitle: "Withdrawal request has been submitted successfully.",
    exitValidatorSubTitle: "It will start cooling down from the next epoch. Please navigate the withdrawals tab to monitor the progress.",
    withdrawalSuccessfullySub: "It may take a few minutes to appear on your balance.",
    withdrawalSuccessfully: "Withdrawal has been submitted successfully.",
    error1: "Failed to get the latest data, please refresh and try again.",
    error2: "Something went wrong. Please contact support or go back and try to use Staking 1.0 in the DApp section.\n\n",
    stepItem1: "Convert",
    stepItem1Part: "XZO EVM to XZO Native",
  };
  
  export default lang;